language: node_js
node_js:
- "stable"
cache:
  directories:
    - "node_modules"

env:
  global:
    - DATABASE_URL : postgres://travis@localhost:5432/travis
    - PRIVATE_KEY : epicemail_secureKey
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
script: npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

services:
- postgres
